prompt --application/deployment/install/install_talent22
begin
--   Manifest
--     INSTALL: INSTALL-talent22
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2022.04.12'
,p_release=>'22.1.2'
,p_default_workspace_id=>7870384460919289
,p_default_application_id=>104
,p_default_id_offset=>30137121571976061
,p_default_owner=>'SACALABICI'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(14079749876474227)
,p_install_id=>wwv_flow_imp.id(10848948754148808)
,p_name=>'talent22'
,p_sequence=>10
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'CREATE TABLE  "HOME" ',
'   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, ',
'	"TITULO" VARCHAR2(30)  , ',
'	"SUBTITULO" VARCHAR2(30)  , ',
'	"TEXTO" VARCHAR2(400)  , ',
'	"IMAGEN" BLOB',
'   ) ',
'/',
'INSERT INTO HOME (TITULO,SUBTITULO,TEXTO) VALUES (''Noticia 1'',''Subtitulo Noticia 1'',''Texto de Noticia 1'')',
'/',
'INSERT INTO HOME (TITULO,SUBTITULO,TEXTO) VALUES (''Noticia 2'',''Subtitulo Noticia 2'',''Texto de Noticia 2'')',
'/',
'INSERT INTO HOME (TITULO,SUBTITULO,TEXTO) VALUES (''Noticia 3'',''Subtitulo Noticia 3'',''Texto de Noticia 3'')',
'/',
'INSERT INTO HOME (TITULO,SUBTITULO,TEXTO) VALUES (''Noticia 4'',''Subtitulo Noticia 4'',''Texto de Noticia 4'')',
'/',
'CREATE TABLE  "USUARIO" ',
'   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, ',
'	"NOMBRE" VARCHAR2(150 CHAR)  NOT NULL ENABLE, ',
'	"APELLIDOS" VARCHAR2(150 CHAR)  NOT NULL ENABLE, ',
'	"CURP" VARCHAR2(600)  NOT NULL ENABLE, ',
'	"GENERO" VARCHAR2(1 CHAR) , ',
'	"NACIMIENTO" DATE NOT NULL ENABLE, ',
'	"DOMICILIO" VARCHAR2(150 CHAR) , ',
'	"CELULAR" NUMBER NOT NULL ENABLE, ',
'	"SANGRE_TIPO" VARCHAR2(20)  NOT NULL ENABLE, ',
'	"TEL_EMERGENCIA" NUMBER NOT NULL ENABLE, ',
'	"ESTATURA" NUMBER NOT NULL ENABLE, ',
'	"EMAIL" VARCHAR2(150 CHAR)  NOT NULL ENABLE, ',
'	"TIPO" VARCHAR2(36)  NOT NULL ENABLE, ',
'	"FOTO" BLOB, ',
'	"PASSWORD" VARCHAR2(250)  NOT NULL ENABLE, ',
'	"EDAD" NUMBER(3,0), ',
'	"PREGUNTA" VARCHAR2(50)  NOT NULL ENABLE, ',
'	"RESPUESTA" VARCHAR2(100)  NOT NULL ENABLE, ',
'	 CONSTRAINT "USUARIO_TIPO_CK" CHECK (tipo in (''ADMIN'',''ASISTENTE'',''GENERAL'')) ENABLE, ',
'	 CONSTRAINT "USUARIO_ID_PK" PRIMARY KEY ("ID")',
'  USING INDEX  ENABLE, ',
'	 CONSTRAINT "USUARIO_GENERO_CK" CHECK (genero in (''F'',''M'',''O'')) ENABLE, ',
'	 CONSTRAINT "USUARIO_EMAIL" UNIQUE ("EMAIL")',
'  USING INDEX  ENABLE, ',
'	 CONSTRAINT "USUARIO_SANGRE_TIPO_CK" CHECK (sangre_tipo in (''A+'',''A-'',''B+'',''B-'',''AB+'',''AB-'',''O+'',''O-'', ''No lo conozco'')) ENABLE',
'   )',
'/',
'',
'CREATE TABLE  "BICI" ',
'   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, ',
'	"NUMERO_SERIE" VARCHAR2(400)   NOT NULL ENABLE, ',
'	"NUMERO" NUMBER NOT NULL ENABLE, ',
'	"ESTADO" VARCHAR2(52)   NOT NULL ENABLE, ',
'	"RODADA" VARCHAR2(400)   NOT NULL ENABLE, ',
'	"CUADRO" VARCHAR2(50)   NOT NULL ENABLE, ',
'	 CONSTRAINT "BICI_ESTADO_CK" CHECK (estado in (''DISPONIBLE'',''RENTADA'',''APARTADA'',''MANTENIMIENTO'')) ENABLE, ',
'	 CONSTRAINT "BICI_ID_PK" PRIMARY KEY ("ID")',
'  USING INDEX  ENABLE, ',
'	 CONSTRAINT "BICI_CUADRO_CK" CHECK (cuadro in (''CHICO'',''MEDIANO'',''GRANDE'')) ENABLE',
'   ) ',
'/',
'',
'CREATE TABLE  "EVENTO" ',
'   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, ',
'	"NOMBRE" VARCHAR2(150 CHAR)   NOT NULL ENABLE, ',
'	"FECHA_HORA" TIMESTAMP (6) NOT NULL ENABLE, ',
'	"DISTANCIA" NUMBER NOT NULL ENABLE, ',
'	"NIVEL" NUMBER NOT NULL ENABLE, ',
'	"RECOMENDACIONES" VARCHAR2(4000 CHAR)  , ',
'	"MIN_RENTA" NUMBER(6,0) NOT NULL ENABLE, ',
'	"MAPA" VARCHAR2(1000)  , ',
'	"MINUTOS_ANTES" NUMBER(2,0) DEFAULT 30 NOT NULL ENABLE, ',
'	"PUNTOPARTIDA" NVARCHAR2(300)   NOT NULL ENABLE, ',
'	"PUNTOLLEGADA" NVARCHAR2(150)  , ',
'	 CONSTRAINT "EVENTO_ID_PK" PRIMARY KEY ("ID")',
'  USING INDEX  ENABLE',
'   ) ',
'/',
'',
'CREATE TABLE  "RENTA" ',
'   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, ',
'	"ID_USUARIO" NUMBER NOT NULL ENABLE, ',
'	"ID_EVENTO" NUMBER NOT NULL ENABLE, ',
'	"ID_BICI" NUMBER NOT NULL ENABLE, ',
'	 CONSTRAINT "RENTA_ID_PK" PRIMARY KEY ("ID")',
'  USING INDEX  ENABLE',
'   ) ',
'/',
'ALTER TABLE  "RENTA" ADD CONSTRAINT "RENTA_USUARIO_ID_FK" FOREIGN KEY ("ID_USUARIO")',
'	  REFERENCES  "USUARIO" ("ID") ON DELETE CASCADE ENABLE',
'/',
'ALTER TABLE  "RENTA" ADD CONSTRAINT "RENTA_EVENTO_ID_FK" FOREIGN KEY ("ID_EVENTO")',
'	  REFERENCES  "EVENTO" ("ID") ON DELETE CASCADE ENABLE',
'/',
'ALTER TABLE  "RENTA" ADD CONSTRAINT "RENTA_BICI_ID_FK" FOREIGN KEY ("ID_BICI")',
'	  REFERENCES  "BICI" ("ID") ON DELETE CASCADE ENABLE',
'/',
''))
);
wwv_flow_imp.component_end;
end;
/
